### PR TITLE
Bundler-compatible gemspec

### PR DESCRIPTION
**Pull request by txus**
Every meme generator needs a bundler-compatible gemspec.

### CODE REVIEW

**Comment by drbrain** [comment]
A gemspec is a generated which is not to be checked in.

Furthermore, the repository is not released code and I do not support unreleased code.

**Comment by txus** [comment]
Yes, I already saw Hoe's methods in the Rakefile, just wanted to make it compatible with Bundler. Sorry for the inconvenience.
I've released my own fork, since I need it for a [wrapper I made](http://github.com/txus/memetalk) for Talkerapp :)

**Comment by drbrain** [comment]
I am confused.

Why you need it to be compatible with bundler? I released your changes the same day I applied them and you have a dependency on (your fork of) meme_generator. Does bundler not understand dependencies?

**Comment by txus** [comment]
Ok, I can see it now. Lapsus! I totally misunderstood bundler dependencies.
I've got rid of any dependency on my fork in [this commit](https://github.com/txus/memetalk/commit/82188d275353a29ac53891b37e38fd0f614dac3e) :)

**Pull request closed without merging**
