### PR TITLE
Code Alignment

### PR DESCRIPTION
**Pull request by dstrelau**
Y U NO ALIGN YOUR MEMES

### CODE REVIEW

**Comment by dstrelau** [comment]
I don't understand pull requests

Apparently I'm supposed to put each individual pull request on a branch, since now this includes all commits from master.

**Comment by achiurizo** [comment]
merge help

**Comment by dstrelau** [comment]
@achiu: as an aside, I went to add Inception, but it seems to want `text2` provided, and sending it all the time (as empty) seems to screw up others that don't use it.

refactoring

**Comment by achiurizo** [comment]
@dstrelau, hmm i guess one way would be to include a default empty string so in the event the user sends one, it should be ok?

**Comment by dstrelau** [comment]
@achiu: no, the problem was that sending `text2` at all (even as empty) was breaking some of the images that only wanted 0 and 1 — the page just returns a 200 OK with no content :( So I need a way to specify the number of lines allowed for each image, I think.

**Comment by achiurizo** [comment]
@dstrelau, i added a feature to add multiple lines at 0939bc79d0b017a868dfb7287425ec0969dc7266. In terms of limiting the numbers, perhaps that could be added in the generator array?

topic branch

**Comment by drbrain** [comment]
applied

I beat it into submission

**Pull request closed without merging**
